name: Build and publish

on:
  push:
    branches:
    - "main"

jobs:
  build-and-publish-head:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.5.0
    - name: Build and publish "head" Docker image
      uses: VaultVulp/gp-docker-action@1.6.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        image-name: albianwarp-landingpage
        image-tag: head
